# Generated by Django 4.0 on 2022-01-21 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profile_facebook_profile_github_profile_instagram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.URLField(blank=True, null=True, verbose_name='Аватар'),
        ),
    ]
