# Generated by Django 4.0 on 2022-01-16 23:37

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(help_text='Введите название статьи', max_length=20, verbose_name='Название статьи')),
                ('article_text', tinymce.models.HTMLField(help_text='Текст статьи', verbose_name='Текст статьи')),
                ('article_about', models.TextField(help_text='О чём статья', null=True, verbose_name='Описание статьи')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('article_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='account.profile', verbose_name='Автор статьи')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(help_text='Название категории', max_length=25, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Coments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coment_text', models.CharField(max_length=200, verbose_name='Текст коментария')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('articles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coments', to='blog.articles', verbose_name='К какой статье?')),
                ('coment_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coments', to='account.profile', verbose_name='Автор коментария')),
            ],
            options={
                'verbose_name': 'Коментарий',
                'verbose_name_plural': 'Коментарии',
            },
        ),
        migrations.AddField(
            model_name='articles',
            name='categories',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='blog.categories', verbose_name='Категория'),
        ),
    ]
