# Generated by Django 4.0 on 2022-01-30 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='fixed',
            field=models.BooleanField(default=False, verbose_name='Закрепить'),
        ),
    ]
