# Generated by Django 4.0 on 2022-02-05 22:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0004_temporarycategories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='temporarycategories',
            options={'verbose_name': 'Временная категория', 'verbose_name_plural': 'Временные категории'},
        ),
        migrations.AddField(
            model_name='articles',
            name='favorites',
            field=models.ManyToManyField(related_name='favourites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='articles',
            name='likes',
            field=models.ManyToManyField(related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
