# Generated by Django 4.0 on 2022-02-10 23:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0008_remove_articles_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favourites', to=settings.AUTH_USER_MODEL, verbose_name='Избранное'),
        ),
    ]
