# Generated by Django 4.1 on 2023-02-28 23:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0010_delete_temporarycategories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'verbose_name': 'Стаття', 'verbose_name_plural': 'Статті'},
        ),
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name': 'Категорія', 'verbose_name_plural': 'Категорії'},
        ),
        migrations.AlterModelOptions(
            name='coments',
            options={'verbose_name': 'Коментар', 'verbose_name_plural': 'Коментарі'},
        ),
        migrations.AddField(
            model_name='categories',
            name='icon',
            field=models.CharField(default='test', max_length=100, verbose_name='Іконка'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='articles',
            name='article_about',
            field=models.CharField(default='testing', max_length=100, verbose_name='Опис статті'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='articles',
            name='article_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL, verbose_name='Автор статті'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='article_text',
            field=tinymce.models.HTMLField(verbose_name='Текст статті'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='article_title',
            field=models.CharField(max_length=50, verbose_name='Назва статті'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='categories',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='blog.categories', verbose_name='Категорія'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favourites', to=settings.AUTH_USER_MODEL, verbose_name='Обране'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='fixed',
            field=models.BooleanField(default=False, verbose_name='Закріпити'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='category',
            field=models.CharField(max_length=100, verbose_name='Категорія'),
        ),
        migrations.AlterField(
            model_name='coments',
            name='articles',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coments', to='blog.articles', verbose_name='До якої статті?'),
        ),
        migrations.AlterField(
            model_name='coments',
            name='coment_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coments', to=settings.AUTH_USER_MODEL, verbose_name='Автор коментаря'),
        ),
        migrations.AlterField(
            model_name='coments',
            name='coment_text',
            field=models.CharField(max_length=200, verbose_name='Текст коментаря'),
        ),
    ]
